name: Docker

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: jd-form
    IMAGE_TAG: production

jobs:
    build:
        name: Build Production Form
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ghcr.io
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
                  file: ./Dockerfile
                  context: .